### ISSUE TITLE
Неполный перевод титров

### ISSUE THREAD

**Issue by AzzyDreemurr13** [TauCetiStation-TranslationDepartment/TauCetiClassic#3]
### Требуемая задача:
Полный перевод титров. Так как произошёл подобный случай:
![image](https://github.com/TauCetiStation-TranslationDepartment/TauCetiClassic/assets/74739991/16b3670c-1758-43f3-9f7c-0bbf9036bc12)
### Ответственные:
@Kiromaka - Отвечает головой за выпуск ПРа
### Сроки: 
15.12.23 - последний крайний срок сдачи. Если ПР будет выпущен во время, будет переведен из кандидатов, в полноценного переводчика
### Проверяющие(Review):
@maleyvich 
@Pivo24 
@AzzyDreemurr13 
### Дополнительная информация:
Оригинальный Ишуй - https://github.com/TauCetiStation/TauCetiClassic/issues/12545

**Comment by Kiromaka** [comment]
Oh shit , работа подъехала
